baseURL = "https://metalheadsanya.github.io/"
languageCode = "en-us"
title = "MetalheadSanya"

[pagination]
  pagerSize = 10

[params]
  description = "Personal tech blog of MetalheadSanya"

[markup]
  [markup.highlight]
    noClasses = false
